install.packages("readxl")
install.packages("tidyr")
library(tidyr)
library(stringr)
library(readxl)
calculadora_medicamentos$APRESENTAÇÃO <- str_replace(calculadora_medicamentos$APRESENTAÇÃO,'SOL INJ', 'Solução Injetável')
calculadora_medicamentos$APRESENTAÇÃO <- str_replace(calculadora_medicamentos$APRESENTAÇÃO, 'Solução Injetável IV', 'Solução Injetável EV')
calculadora_medicamentos$APRESENTAÇÃO <- str_replace(calculadora_medicamentos$APRESENTAÇÃO, 'CT', 'Caixa')
calculadora_medicamentos$APRESENTAÇÃO <- str_replace(calculadora_medicamentos$APRESENTAÇÃO, 'FR PLAS TRANS', 'Frasco Plástico Transparente')
calculadora_medicamentos$APRESENTAÇÃO <- str_replace(calculadora_medicamentos$APRESENTAÇÃO, 'Caixa', 'Contem')
calculadora_medicamentos$APRESENTAÇÃO <- str_replace(calculadora_medicamentos$APRESENTAÇÃO, 'MG I/ML', 'MG/ML')
calculadora_medicamentos$APRESENTAÇÃO <- str_replace(calculadora_medicamentos$APRESENTAÇÃO, 'FA VD TRANS', 'Frasco-Ampola Vidro Transparente')
calculadora_medicamentos$APRESENTAÇÃO <- str_replace(calculadora_medicamentos$APRESENTAÇÃO, '/', ' / ')

calculadora_medicamentos2 <- calculadora_medicamentos %>% filter(grepl('/', APRESENTAÇÃO))
library(dplyr)
library(stringr)

calculadora_medicamentos2<- calculadora_medicamentos %>% filter(str_detect(calculadora_medicamentos$APRESENTAÇÃO, " / "))
View(calculadora_medicamentos2)
